# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Thomas Barker
title: Software Engineer
email: thomasjakebarker@outlook.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  TechTurtle11
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: thomas.barker2001
linkedin_username: thomas-barker2001
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
## - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Hi my name is Thomas Barker, I'm a Software Developer currently specialising in application development in <mark>python</mark> and <mark>C++</mark>.
  I am currently working for BAE Systems Digital Intelligence on some exciting projects.

  I enjoy developing modern and scalable software solutions to unconventional problems. I like working to create clean and efficient developer experiences
  to focus on code quality and reduce overall development time. I have worked with a range of different languages and frameworks and I am always looking for opportunities to work with something new.
  The things that I currently have the most experience working with are <mark>Python</mark>, <mark>C++</mark>, <mark>Docker</mark>, <mark>Java</mark>, <mark>Jenkins</mark>, <mark>Git</mark> and <mark>Red Hat Enterprise Linux</mark>.


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                # other value (or no value) means no border will be displayed
        title: BAE Systems Digital Intelligence
        sub_title: Software Engineer (Graduate)
        caption: September 2022 - present
        link: https://www.baesystems.com/en/digital
        description: | # this will include new lines to allow paragraphs
          I began my graduate career at BAE Systems by playing a pivotal role in uplifting a test harness in <mark>Ruby</mark> and <mark>Rspec</mark>,
          introducing continuous integration to ensure top-quality results.

          My work on this project gave me the opportunity to reconnect with some of the colleagues I worked with during my internship,
          and I was offered the opportunity to join the team delivering several significant releases at BAE Systems.
          My contributions to these releases were so impactful that I was awarded for my outstanding work.

          My work on this project gave me the opportunity to reconnect with some of the colleagues I worked with during my internship,
          This led me to being offered the chance to do some prototyping and design work 
          This work involved redesigning and extending the test harness that I had initially worked on as an intern.
          I assessed the previous implementation to produce detailed requirements, which I then used to design and implement the new solution.

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
          # other value (or no value) means no border will be displayed
        title: BAE Systems Digital Intelligence
        sub_title: Software Engineer (Intern)
        caption: June 2021 - September 2021
        link: https://www.baesystems.com/en/digital
        description: | # this will include new lines to allow paragraphs
          During my internship at BAE Systems, I had the opportunity to work on a challenging project that involved extending a test harness using python.
          This experience taught me a great deal about practical development on RH-based Linux OSs, and I gained valuable hands-on experience working with these technologies.

          One of my proudest achievements during this internship was introducing continuous integration to the test harness, using a <mark>Jenkins</mark> pipeline.
          This addition helped to streamline our development process and improving confidence in produced code.

          As I worked on this project, I was constantly seeking out ways to improve our methods and tools. I researched and tested new approaches, and shared my findings with my colleagues,
          helping us all to work more efficiently and effectively.

          Overall, my experience working on this project was incredibly rewarding. I learned a great deal about software engineering,
          honed my skills in <mark>python</mark>, <mark>docker</mark>, and continuous integration techniques, and gained my first practical <mark>RH-based OS Linux</mark> development experience.

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
          # other value (or no value) means no border will be displayed
        title: Cascade
        sub_title: Volunteer Backend Software Engineer
        caption: June 2020 - Dec 2020
        description: | # this will include new lines to allow paragraphs
          During my time at Cambridge, I was volunteered to help a friend develop the backend for there sustainable choice app/web application. 
          I led the backend coding team on this project, working on creating the web API using <mark>Django</mark> <mark>REST</mark> framework and how this could be deployed on a linux server.
          This was my first opportunity to lead software engineers and deploying an application, I feel this opportunity has given me the drive to always want to try new develop myself and other engineers

      - layout: left
          # other value (or no value) means no border will be displayed
        title: Open Roberta
        sub_title: Student Software Developer
        link: https://github.com/OpenRoberta/openroberta-lab
        caption: June 2020 - September 2020
        description: | # this will include new lines to allow paragraphs
          As part of the googles summer of code scheme I extended Open Roberta’s robot simulation stack machine interpreter in <mark>typescript</mark>
          to allow users to see the current code executing by highlighting the code blocks. I also developed debugging functionality for 
          the robot simulation in typescript for users. I was able to complete final testing and provided a demo of my work as a part of the end of 
          project presentation which was well received by the Senior team members.

          This was my first time working on a preestablished open-source codebase which was fascinating, I also learnt a lot by robotics and compilers which are a personal areas of interest of mine.
  - title: Education
    layout: list
    content:
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
          # other value (or no value) means no border will be displayed
        title: Pembroke College, University Of Cambridge
        sub_title: BA Computer Science
        caption: 2019-2022
        description: | # this will include new lines to allow paragraphs
          During my degree at the University Of Cambridge I learnt lots of key skills such as team work and project management.
          Although we mostly focused on software development and the principles of programming I use lot of these skills to my advantage
          in my day to day work. My course focused mostly of practical concepts with languages expected to be learnt alongside modules. Due to this approach I learnt the ability 
          to quickly pick up a new languages and technologies some of these include: <mark>OCaml</mark>, <mark>Java</mark>, <mark>C/C++</mark>, <mark>Python</mark>, <mark>SQL</mark>, <mark>Prolog</mark>, <mark>Git</mark> and <mark>Verilog</mark>.
          Some of my favorite modules included: <mark>Concurrent and Distributed Computing</mark>, 
          <mark>Advanced Computer Architecture</mark> and <mark>Optimising Compilers</mark>. 

          While at Cambridge I spent a lot of my free time attending various Hackathons, exploring the gorgeous Cambridgeshire countryside and partaking in various societies.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Bluetooth Low Energy Geolocation
        link: https://github.com/TechTurtle11/ble-geolocation
        link_text: ble-geolocation
        description: | # this will include new lines to allow paragraphs
          **[Link To Dissertation In Full](./assets/geolocation_in_a_rainforest.pdf)**

          Traditionally GPS is used to provide radiolocation outside with successful results;
          however in some environments such as the rainforest this provides inaccurate results due
          to environmental factors. The project aimed to build a Bluetooth low energy (BLE)
          localisation system to produce more accurate results. I received a first in my Dissertation and the project results were a promising
          indicator that the model may be able to be applied to mapping in the rainforest.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs

      When I’m not sat at my desk I am very active and spend most of my time outdoors. I do a few sports such as mountain biking,
      walking and running as well as trying to make time for things like rock climbing and swimming.

      Finally during the rest of my free time you will either find me fixing my bike again, at the cinema watching the latest release or down at the pub with some friends.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
